### ISSUE TITLE
Serial TX / RX 

### ISSUE THREAD

**Issue by jarcikw** [TheSDTM/esphome-SDM-enery-meter#1]
Hi,
I try to connect with SDM630 and I have probably some problem with communication
![image](https://user-images.githubusercontent.com/35450305/74592508-63b2e500-5022-11ea-95fc-cfcee2897752.png)
I have switched TX witth RX in config but without result

my config:
```
substitutions:
  name: korytarz_sdm630
esphome:
  name: korytarz_sdm630
  platform: ESP8266
  board: esp01_1m
  includes:
    - sdm/SDM_Config_User.h
    - sdm/SDM.h
    - sdm/sdm_esphome.h

uart:
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
  stop_bits: 1
```

Previously i have configured with Tasmota and it was working fine 
![image](https://user-images.githubusercontent.com/35450305/74592458-f43cf580-5021-11ea-99c7-d6dd6d6b396e.png)

Do I need to change GPIO configuration in some files?
